# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 803)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.widget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.widget)
        self.lineEdit_isin = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_isin.setObjectName("lineEdit_isin")
        self.verticalLayout.addWidget(self.lineEdit_isin)
        self.lineEdit_desc = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_desc.setObjectName("lineEdit_desc")
        self.verticalLayout.addWidget(self.lineEdit_desc)
        self.lineEdit_qta = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_qta.setObjectName("lineEdit_qta")
        self.verticalLayout.addWidget(self.lineEdit_qta)
        self.lineEdit_inv = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_inv.setObjectName("lineEdit_inv")
        self.verticalLayout.addWidget(self.lineEdit_inv)
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setEnabled(True)
        self.menuFile.setObjectName("menuFile")
        self.menuModifica = QtWidgets.QMenu(parent=self.menubar)
        self.menuModifica.setObjectName("menuModifica")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setCheckable(False)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.ApplicationExit)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuModifica.addSeparator()
        self.menuModifica.addSeparator()
        self.menuModifica.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuModifica.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Todo"))
        self.lineEdit_isin.setText(_translate("MainWindow", "isin"))
        self.lineEdit_desc.setText(_translate("MainWindow", "desc"))
        self.lineEdit_qta.setText(_translate("MainWindow", "qta"))
        self.lineEdit_inv.setText(_translate("MainWindow", "inv€"))
        self.addButton.setText(_translate("MainWindow", "Add Todo"))
        self.saveButton.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuModifica.setTitle(_translate("MainWindow", "Modifica"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
